import { DomainGroup } from '@/utils/types/Domain';
import {
  FaServer,
  FaDesktop,
  FaGears,
  FaShieldHalved,
  FaChartLine,
  FaMobileScreen,
  FaRobot,
  FaGamepad,
  FaCloud,
  FaLink,
  FaMicrochip,
  FaBug,
  FaGraduationCap,
  FaMasksTheater,
  FaMicroscope,
  FaPaintbrush,
  FaPalette,
  FaScaleBalanced,
  FaBullhorn,
  FaHandshake,
  FaPeopleGroup,
  FaUserDoctor,
  FaHotel,
  FaPlane,
  FaUtensils,
  FaTruck,
  FaBox,
  FaIndustry,
  FaScrewdriverWrench,
  FaHospital,
  FaLeaf,
  FaSeedling,
  FaNewspaper,
  FaBrain,
  FaBuilding,
  FaMoneyBillTrendUp,
  FaCreditCard,
  FaVault,
  FaChartPie,
  FaCoins,
  FaArrowTrendUp,
  FaShieldHeart,
  FaCarSide,
  FaHouseChimney,
  FaCalculator,
  FaLaptopCode,
  FaObjectGroup,
} from 'react-icons/fa6';

export const domainGroups: DomainGroup[] = [
  {
    key: 'technology',
    group: 'domain_group_technology',
    icon: FaGears,
    domains: [
      {
        key: 'backend',
        name: 'domain_backend',
        icon: FaServer,
        description: 'domain_backend_desc',
        children: [
          'domain_backend_child_nodejs',
          'domain_backend_child_python',
          'domain_backend_child_java',
          'domain_backend_child_go',
          'domain_backend_child_ruby',
          'domain_backend_child_php',
          'domain_backend_child_dotnet',
        ],
      },
      {
        key: 'frontend',
        name: 'domain_frontend',
        icon: FaDesktop,
        description: 'domain_frontend_desc',
        children: [
          'domain_frontend_child_react',
          'domain_frontend_child_vue',
          'domain_frontend_child_angular',
          'domain_frontend_child_svelte',
          'domain_frontend_child_javascript',
          'domain_frontend_child_typescript',
          'domain_frontend_child_htmlcss',
        ],
      },
      {
        key: 'devops',
        name: 'domain_devops',
        icon: FaGears,
        description: 'domain_devops_desc',
        children: [
          'domain_devops_child_docker',
          'domain_devops_child_kubernetes',
          'domain_devops_child_cicd',
          'domain_devops_child_aws',
          'domain_devops_child_azure',
          'domain_devops_child_gcp',
          'domain_devops_child_linux',
        ],
      },
      {
        key: 'security',
        name: 'domain_security',
        icon: FaShieldHalved,
        description: 'domain_security_desc',
        children: [
          'domain_security_child_pentesting',
          'domain_security_child_cryptography',
          'domain_security_child_network',
          'domain_security_child_web',
        ],
      },
      {
        key: 'datascience',
        name: 'domain_datascience',
        icon: FaChartLine,
        description: 'domain_datascience_desc',
        children: [
          'domain_datascience_child_python',
          'domain_datascience_child_r',
          'domain_datascience_child_sql',
          'domain_datascience_child_statistics',
          'domain_datascience_child_visualization',
        ],
      },
      {
        key: 'mobile',
        name: 'domain_mobile',
        icon: FaMobileScreen,
        description: 'domain_mobile_desc',
        children: [
          'domain_mobile_child_ios',
          'domain_mobile_child_android',
          'domain_mobile_child_reactnative',
          'domain_mobile_child_flutter',
          'domain_mobile_child_kotlin',
          'domain_mobile_child_swift',
        ],
      },
      {
        key: 'aiml',
        name: 'domain_aiml',
        icon: FaRobot,
        description: 'domain_aiml_desc',
        children: [
          'domain_aiml_child_machinelearning',
          'domain_aiml_child_deeplearning',
          'domain_aiml_child_nlp',
          'domain_aiml_child_computervision',
        ],
      },
      {
        key: 'game',
        name: 'domain_game',
        icon: FaGamepad,
        description: 'domain_game_desc',
        children: [
          'domain_game_child_unity',
          'domain_game_child_unreal',
          'domain_game_child_gamedesign',
          'domain_game_child_graphics',
        ],
      },
      {
        key: 'cloud',
        name: 'domain_cloud',
        icon: FaCloud,
        description: 'domain_cloud_desc',
        children: [
          'domain_cloud_child_aws',
          'domain_cloud_child_azure',
          'domain_cloud_child_gcp',
          'domain_cloud_child_architecture',
          'domain_cloud_child_serverless',
        ],
      },
      {
        key: 'blockchain',
        name: 'domain_blockchain',
        icon: FaLink,
        description: 'domain_blockchain_desc',
        children: [
          'domain_blockchain_child_smartcontracts',
          'domain_blockchain_child_dapps',
          'domain_blockchain_child_crypto',
          'domain_blockchain_child_web3',
        ],
      },
      {
        key: 'iot',
        name: 'domain_iot',
        icon: FaMicrochip,
        description: 'domain_iot_desc',
        children: [
          'domain_iot_child_embedded',
          'domain_iot_child_sensors',
          'domain_iot_child_protocols',
          'domain_iot_child_edge',
        ],
      },
      {
        key: 'qa',
        name: 'domain_qa',
        icon: FaBug,
        description: 'domain_qa_desc',
        children: [
          'domain_qa_child_automation',
          'domain_qa_child_manual',
          'domain_qa_child_performance',
          'domain_qa_child_security',
        ],
      },
      {
        key: 'embedded',
        name: 'domain_embedded',
        icon: FaMicrochip,
        description: 'domain_embedded_desc',
        children: [
          'domain_embedded_child_c',
          'domain_embedded_child_cpp',
          'domain_embedded_child_arm',
          'domain_embedded_child_rtos',
          'domain_embedded_child_iot',
          'domain_embedded_child_firmware',
        ],
      },
    ],
  },
  {
    key: 'design',
    group: 'domain_group_design',
    icon: FaPalette,
    domains: [
      {
        key: 'uiux',
        name: 'domain_uiux',
        icon: FaLaptopCode,
        description: 'domain_uiux_desc',
        children: [
          'domain_uiux_child_uxresearch',
          'domain_uiux_child_uidesign',
          'domain_uiux_child_interaction',
          'domain_uiux_child_usability',
          'domain_uiux_child_ia',
          'domain_uiux_child_designsystems',
        ],
      },
      {
        key: 'graphic',
        name: 'domain_graphic',
        icon: FaPaintbrush,
        description: 'domain_graphic_desc',
        children: [
          'domain_graphic_child_brand',
          'domain_graphic_child_print',
          'domain_graphic_child_digital',
          'domain_graphic_child_motion',
          'domain_graphic_child_typography',
          'domain_graphic_child_identity',
        ],
      },
      {
        key: 'product',
        name: 'domain_product',
        icon: FaObjectGroup,
        description: 'domain_product_desc',
        children: [
          'domain_product_child_strategy',
          'domain_product_child_research',
          'domain_product_child_roadmap',
          'domain_product_child_agile',
          'domain_product_child_analytics',
          'domain_product_child_gtm',
        ],
      },
    ],
  },
  {
    key: 'business',
    group: 'domain_group_business',
    icon: FaChartLine,
    domains: [
      {
        key: 'business_strategy',
        name: 'domain_business_strategy',
        icon: FaChartLine,
        description: 'domain_business_strategy_desc',
        children: [
          'domain_business_strategy_child_planning',
          'domain_business_strategy_child_development',
          'domain_business_strategy_child_digital',
          'domain_business_strategy_child_ecommerce',
          'domain_business_strategy_child_innovation',
        ],
      },
      {
        key: 'marketing',
        name: 'domain_marketing',
        icon: FaBullhorn,
        description: 'domain_marketing_desc',
        children: [
          'domain_marketing_child_digital',
          'domain_marketing_child_content',
          'domain_marketing_child_social',
          'domain_marketing_child_brand',
          'domain_marketing_child_research',
        ],
      },
      {
        key: 'sales',
        name: 'domain_sales',
        icon: FaHandshake,
        description: 'domain_sales_desc',
        children: [
          'domain_sales_child_b2b',
          'domain_sales_child_b2c',
          'domain_sales_child_strategy',
          'domain_sales_child_account',
          'domain_sales_child_lead',
        ],
      },
      {
        key: 'finance_accounting',
        name: 'domain_finance_accounting',
        icon: FaChartLine,
        description: 'domain_finance_accounting_desc',
        children: [
          'domain_finance_accounting_child_analysis',
          'domain_finance_accounting_child_accounting',
          'domain_finance_accounting_child_investment',
          'domain_finance_accounting_child_risk',
          'domain_finance_accounting_child_tax',
        ],
      },
      {
        key: 'hr',
        name: 'domain_hr',
        icon: FaPeopleGroup,
        description: 'domain_hr_desc',
        children: [
          'domain_hr_child_acquisition',
          'domain_hr_child_development',
          'domain_hr_child_performance',
          'domain_hr_child_compensation',
          'domain_hr_child_analytics',
        ],
      },
    ],
  },
  {
    key: 'legal',
    group: 'domain_group_legal',
    icon: FaScaleBalanced,
    domains: [
      {
        key: 'legal',
        name: 'domain_legal',
        icon: FaScaleBalanced,
        description: 'domain_legal_desc',
        children: [
          'domain_legal_child_corporate',
          'domain_legal_child_ip',
          'domain_legal_child_contract',
          'domain_legal_child_employment',
          'domain_legal_child_compliance',
        ],
      },
    ],
  },
  {
    key: 'education',
    group: 'domain_group_education',
    icon: FaGraduationCap,
    domains: [
      {
        key: 'teaching',
        name: 'domain_teaching',
        icon: FaGraduationCap,
        description: 'domain_teaching_desc',
        children: [
          'domain_teaching_child_k12',
          'domain_teaching_child_higher',
          'domain_teaching_child_online',
          'domain_teaching_child_special',
          'domain_teaching_child_stem',
          'domain_teaching_child_language',
        ],
      },
      {
        key: 'curriculum',
        name: 'domain_curriculum',
        icon: FaGraduationCap,
        description: 'domain_curriculum_desc',
        children: [
          'domain_curriculum_child_development',
          'domain_curriculum_child_edtech',
          'domain_curriculum_child_assessment',
          'domain_curriculum_child_analytics',
          'domain_curriculum_child_instructional',
          'domain_curriculum_child_elearning',
        ],
      },
    ],
  },
  {
    key: 'arts',
    group: 'domain_group_arts',
    icon: FaMasksTheater,
    domains: [
      {
        key: 'visual_arts',
        name: 'domain_visual_arts',
        icon: FaPaintbrush,
        description: 'domain_visual_arts_desc',
        children: [
          'domain_visual_arts_child_digital',
          'domain_visual_arts_child_traditional',
          'domain_visual_arts_child_animation',
          'domain_visual_arts_child_photography',
          'domain_visual_arts_child_illustration',
          'domain_visual_arts_child_sculpture',
        ],
      },
      {
        key: 'performing_arts',
        name: 'domain_performing_arts',
        icon: FaMasksTheater,
        description: 'domain_performing_arts_desc',
        children: [
          'domain_performing_arts_child_music',
          'domain_performing_arts_child_theater',
          'domain_performing_arts_child_dance',
          'domain_performing_arts_child_film',
          'domain_performing_arts_child_direction',
          'domain_performing_arts_child_performance',
        ],
      },
      {
        key: 'conservatory_music',
        name: 'domain_conservatory_music',
        icon: FaMasksTheater,
        description: 'domain_conservatory_music_desc',
        children: [
          'domain_conservatory_music_child_theory',
          'domain_conservatory_music_child_instrumental',
          'domain_conservatory_music_child_orchestration',
          'domain_conservatory_music_child_composition',
          'domain_conservatory_music_child_conducting',
          'domain_conservatory_music_child_vocal',
        ],
      },
    ],
  },
  {
    key: 'science',
    group: 'domain_group_science',
    icon: FaMicroscope,
    domains: [
      {
        key: 'research',
        name: 'domain_research',
        icon: FaMicroscope,
        description: 'domain_research_desc',
        children: [
          'domain_research_child_methods',
          'domain_research_child_analysis',
          'domain_research_child_writing',
          'domain_research_child_lab',
        ],
      },
      {
        key: 'applied_science',
        name: 'domain_applied_science',
        icon: FaMicroscope,
        description: 'domain_applied_science_desc',
        children: [
          'domain_applied_science_child_physics',
          'domain_applied_science_child_chemistry',
          'domain_applied_science_child_biology',
          'domain_applied_science_child_environmental',
        ],
      },
    ],
  },
  {
    key: 'engineering',
    group: 'domain_group_engineering',
    icon: FaGears,
    domains: [
      {
        key: 'mechanical',
        name: 'domain_mechanical',
        icon: FaGears,
        description: 'domain_mechanical_desc',
        children: [
          'domain_mechanical_child_cad',
          'domain_mechanical_child_solidworks',
          'domain_mechanical_child_thermodynamics',
          'domain_mechanical_child_materials',
          'domain_mechanical_child_manufacturing',
        ],
      },
      {
        key: 'electrical',
        name: 'domain_electrical',
        icon: FaMicrochip,
        description: 'domain_electrical_desc',
        children: [
          'domain_electrical_child_industrial',
          'domain_electrical_child_power',
          'domain_electrical_child_circuit',
          'domain_electrical_child_fpga',
          'domain_electrical_child_chip',
          'domain_electrical_child_digital',
        ],
      },
      {
        key: 'embedded',
        name: 'domain_embedded',
        icon: FaMicrochip,
        description: 'domain_embedded_desc',
        children: [
          'domain_embedded_child_c',
          'domain_embedded_child_cpp',
          'domain_embedded_child_arm',
          'domain_embedded_child_rtos',
          'domain_embedded_child_iot',
          'domain_embedded_child_firmware',
        ],
      },
      {
        key: 'hvac_piping',
        name: 'domain_hvac_piping',
        icon: FaGears,
        description: 'domain_hvac_piping_desc',
        children: [
          'domain_hvac_piping_child_hvac',
          'domain_hvac_piping_child_piping',
          'domain_hvac_piping_child_ductwork',
          'domain_hvac_piping_child_revit',
          'domain_hvac_piping_child_chiller',
          'domain_hvac_piping_child_pump',
          'domain_hvac_piping_child_fire',
          'domain_hvac_piping_child_plumbing',
        ],
      },
    ],
  },
  {
    key: 'hospitality',
    group: 'domain_group_hospitality',
    icon: FaHotel,
    domains: [
      {
        key: 'tourism',
        name: 'domain_tourism',
        icon: FaPlane,
        description: 'domain_tourism_desc',
        children: [
          'domain_tourism_child_planning',
          'domain_tourism_child_management',
          'domain_tourism_child_services',
          'domain_tourism_child_marketing',
        ],
      },
      {
        key: 'hotel_management',
        name: 'domain_hotel_management',
        icon: FaHotel,
        description: 'domain_hotel_management_desc',
        children: [
          'domain_hotel_child_operations',
          'domain_hotel_child_front',
          'domain_hotel_child_housekeeping',
          'domain_hotel_child_food',
          'domain_hotel_child_revenue',
        ],
      },
      {
        key: 'restaurant_management',
        name: 'domain_restaurant_management',
        icon: FaUtensils,
        description: 'domain_restaurant_management_desc',
        children: [
          'domain_restaurant_child_operations',
          'domain_restaurant_child_kitchen',
          'domain_restaurant_child_menu',
          'domain_restaurant_child_safety',
          'domain_restaurant_child_service',
        ],
      },
    ],
  },
  {
    key: 'logistics',
    group: 'domain_group_logistics',
    icon: FaTruck,
    domains: [
      {
        key: 'transportation',
        name: 'domain_transportation',
        icon: FaTruck,
        description: 'domain_transportation_desc',
        children: [
          'domain_transportation_child_fleet',
          'domain_transportation_child_route',
          'domain_transportation_child_planning',
          'domain_transportation_child_shipping',
        ],
      },
      {
        key: 'logistics_management',
        name: 'domain_logistics_management',
        icon: FaBox,
        description: 'domain_logistics_management_desc',
        children: [
          'domain_logistics_child_supply',
          'domain_logistics_child_warehouse',
          'domain_logistics_child_inventory',
          'domain_logistics_child_distribution',
        ],
      },
    ],
  },
  {
    key: 'manufacturing',
    group: 'domain_group_manufacturing',
    icon: FaIndustry,
    domains: [
      {
        key: 'production',
        name: 'domain_production',
        icon: FaIndustry,
        description: 'domain_production_desc',
        children: [
          'Production Planning',
          'Quality Control',
          'Process Optimization',
          'Manufacturing Operations',
        ],
      },
      {
        key: 'skilled_labor',
        name: 'domain_skilled_labor',
        icon: FaScrewdriverWrench,
        description: 'domain_skilled_labor_desc',
        children: [
          'Assembly',
          'Machine Operation',
          'Maintenance',
          'Craftsmanship',
        ],
      },
    ],
  },
  {
    key: 'healthcare',
    group: 'domain_group_healthcare',
    icon: FaHospital,
    domains: [
      {
        key: 'nursing',
        name: 'domain_nursing',
        icon: FaUserDoctor,
        description: 'domain_nursing_desc',
        children: [
          'Clinical Nursing',
          'Emergency Care',
          'Patient Care',
          'Medical Procedures',
        ],
      },
      {
        key: 'pharmacy',
        name: 'domain_pharmacy',
        icon: FaHospital,
        description: 'domain_pharmacy_desc',
        children: [
          'Pharmacology',
          'Drug Interactions',
          'Pharmaceutical Care',
          'Clinical Pharmacy',
        ],
      },
      {
        key: 'healthcare_admin',
        name: 'domain_healthcare_admin',
        icon: FaHospital,
        description: 'domain_healthcare_admin_desc',
        children: [
          'Hospital Management',
          'Healthcare Policy',
          'Medical Records',
          'Healthcare Operations',
        ],
      },
    ],
  },
  {
    key: 'environmental',
    group: 'domain_group_environmental',
    icon: FaLeaf,
    domains: [
      {
        key: 'environmental_management',
        name: 'domain_environmental_management',
        icon: FaLeaf,
        description: 'domain_environmental_management_desc',
        children: [
          'Environmental Impact Assessment',
          'Waste Management',
          'Conservation',
          'Sustainability',
        ],
      },
      {
        key: 'renewable_energy',
        name: 'domain_renewable_energy',
        icon: FaLeaf,
        description: 'domain_renewable_energy_desc',
        children: [
          'Solar Energy',
          'Wind Power',
          'Hydroelectric',
          'Energy Storage',
        ],
      },
    ],
  },
  {
    key: 'agriculture',
    group: 'domain_group_agriculture',
    icon: FaSeedling,
    domains: [
      {
        key: 'agribusiness',
        name: 'domain_agribusiness',
        icon: FaSeedling,
        description: 'domain_agribusiness_desc',
        children: [
          'Farm Management',
          'Agricultural Economics',
          'Supply Chain',
          'Food Production',
        ],
      },
      {
        key: 'food_science',
        name: 'domain_food_science',
        icon: FaSeedling,
        description: 'domain_food_science_desc',
        children: [
          'Food Processing',
          'Food Safety',
          'Product Development',
          'Quality Control',
        ],
      },
    ],
  },
  {
    key: 'media',
    group: 'domain_group_media',
    icon: FaNewspaper,
    domains: [
      {
        key: 'journalism',
        name: 'domain_journalism',
        icon: FaNewspaper,
        description: 'domain_journalism_desc',
        children: [
          'News Writing',
          'Investigative Journalism',
          'Digital Media',
          'Broadcasting',
        ],
      },
      {
        key: 'public_relations',
        name: 'domain_public_relations',
        icon: FaNewspaper,
        description: 'domain_public_relations_desc',
        children: [
          'Media Relations',
          'Crisis Communication',
          'Corporate Communications',
          'Public Affairs',
        ],
      },
    ],
  },
  {
    key: 'psychology',
    group: 'domain_group_psychology',
    icon: FaBrain,
    domains: [
      {
        key: 'clinical_psychology',
        name: 'domain_clinical_psychology',
        icon: FaBrain,
        description: 'domain_clinical_psychology_desc',
        children: [
          'Psychological Assessment',
          'Therapy',
          'Mental Health',
          'Behavioral Analysis',
        ],
      },
      {
        key: 'organizational_psychology',
        name: 'domain_organizational_psychology',
        icon: FaBrain,
        description: 'domain_organizational_psychology_desc',
        children: [
          'Workplace Behavior',
          'Employee Assessment',
          'Team Dynamics',
          'Leadership Development',
        ],
      },
    ],
  },
  {
    key: 'architecture',
    group: 'domain_group_architecture',
    icon: FaBuilding,
    domains: [
      {
        key: 'architectural_design',
        name: 'domain_architectural_design',
        icon: FaBuilding,
        description: 'domain_architectural_design_desc',
        children: [
          'Building Design',
          'CAD',
          'Sustainable Architecture',
          'Urban Planning',
        ],
      },
      {
        key: 'construction_management',
        name: 'domain_construction_management',
        icon: FaBuilding,
        description: 'domain_construction_management_desc',
        children: [
          'Project Management',
          'Construction Planning',
          'Cost Estimation',
          'Site Supervision',
        ],
      },
    ],
  },
  {
    key: 'banking',
    group: 'domain_group_banking',
    icon: FaMoneyBillTrendUp,
    domains: [
      {
        key: 'retail_banking',
        name: 'domain_retail_banking',
        icon: FaCreditCard,
        description: 'domain_retail_banking_desc',
        children: [
          'Personal Banking',
          'Credit Cards',
          'Mortgages',
          'Consumer Lending',
          'Digital Banking',
        ],
      },
      {
        key: 'investment_banking',
        name: 'domain_investment_banking',
        icon: FaChartPie,
        description: 'domain_investment_banking_desc',
        children: [
          'Corporate Finance',
          'Mergers & Acquisitions',
          'Capital Markets',
          'Securities Trading',
          'Financial Advisory',
        ],
      },
      {
        key: 'wealth_management',
        name: 'domain_wealth_management',
        icon: FaVault,
        description: 'domain_wealth_management_desc',
        children: [
          'Portfolio Management',
          'Estate Planning',
          'Private Banking',
          'Asset Management',
          'Investment Strategy',
        ],
      },
      {
        key: 'risk_compliance',
        name: 'domain_risk_compliance',
        icon: FaShieldHalved,
        description: 'domain_risk_compliance_desc',
        children: [
          'Risk Assessment',
          'Regulatory Compliance',
          'Anti-Money Laundering',
          'Credit Risk',
          'Market Risk',
        ],
      },
    ],
  },
  {
    key: 'investment',
    group: 'domain_group_investment',
    icon: FaChartLine,
    domains: [
      {
        key: 'securities_trading',
        name: 'domain_securities_trading',
        icon: FaArrowTrendUp,
        description: 'domain_securities_trading_desc',
        children: [
          'Equity Trading',
          'Fixed Income',
          'Derivatives',
          'Forex Trading',
          'Technical Analysis',
        ],
      },
      {
        key: 'portfolio_management',
        name: 'domain_portfolio_management',
        icon: FaChartPie,
        description: 'domain_portfolio_management_desc',
        children: [
          'Asset Allocation',
          'Risk Management',
          'Performance Analysis',
          'Investment Strategy',
          'Fund Management',
        ],
      },
      {
        key: 'alternative_investments',
        name: 'domain_alternative_investments',
        icon: FaCoins,
        description: 'domain_alternative_investments_desc',
        children: [
          'Private Equity',
          'Hedge Funds',
          'Real Estate Investment',
          'Venture Capital',
          'Cryptocurrency',
        ],
      },
      {
        key: 'market_analysis',
        name: 'domain_market_analysis',
        icon: FaChartLine,
        description: 'domain_market_analysis_desc',
        children: [
          'Fundamental Analysis',
          'Market Research',
          'Economic Analysis',
          'Quantitative Analysis',
          'ESG Investment',
        ],
      },
    ],
  },
  {
    key: 'insurance',
    group: 'domain_group_insurance',
    icon: FaShieldHeart,
    domains: [
      {
        key: 'life_health_insurance',
        name: 'domain_life_health_insurance',
        icon: FaShieldHeart,
        description: 'domain_life_health_insurance_desc',
        children: [
          'Life Insurance',
          'Health Insurance',
          'Medical Claims',
          'Group Insurance',
          'Insurance Planning',
        ],
      },
      {
        key: 'property_casualty',
        name: 'domain_property_casualty',
        icon: FaHouseChimney,
        description: 'domain_property_casualty_desc',
        children: [
          'Property Insurance',
          'Auto Insurance',
          'Liability Coverage',
          'Commercial Insurance',
          'Risk Assessment',
        ],
      },
      {
        key: 'insurance_underwriting',
        name: 'domain_insurance_underwriting',
        icon: FaCalculator,
        description: 'domain_insurance_underwriting_desc',
        children: [
          'Risk Evaluation',
          'Policy Pricing',
          'Claims Analysis',
          'Actuarial Science',
          'Underwriting Guidelines',
        ],
      },
      {
        key: 'claims_management',
        name: 'domain_claims_management',
        icon: FaCarSide,
        description: 'domain_claims_management_desc',
        children: [
          'Claims Processing',
          'Investigation',
          'Settlement',
          'Fraud Detection',
          'Customer Service',
        ],
      },
    ],
  },
];
