import { DomainGroup } from '@/utils/types/Domain';
import {
  FaServer,
  FaDesktop,
  FaGears,
  FaShieldHalved,
  FaChartLine,
  FaMobileScreen,
  FaRobot,
  FaGamepad,
  FaCloud,
  FaLink,
  FaMicrochip,
  FaBug,
  FaGraduationCap,
  FaMasksTheater,
  FaMicroscope,
  FaPaintbrush,
  FaPalette,
  FaScaleBalanced,
  FaBullhorn,
  FaHandshake,
  FaPeopleGroup,
  FaUserDoctor,
  FaHotel,
  FaPlane,
  FaUtensils,
  FaTruck,
  FaBox,
  FaIndustry,
  FaScrewdriverWrench,
  FaHospital,
  FaLeaf,
  FaSeedling,
  FaNewspaper,
  FaBrain,
  FaBuilding,
  FaMoneyBillTrendUp,
  FaCreditCard,
  FaVault,
  FaChartPie,
  FaCoins,
  FaArrowTrendUp,
  FaShieldHeart,
  FaCarSide,
  FaHouseChimney,
  FaCalculator,
  FaLaptopCode,
  FaObjectGroup,
} from 'react-icons/fa6';

export const domainGroups: DomainGroup[] = [
  {
    key: 'technology',
    group: 'domain_group_technology',
    icon: FaGears,
    domains: [
      {
        key: 'backend',
        name: 'domain_backend',
        icon: FaServer,
        description: 'domain_backend_desc',
        children: ['Node.js', 'Python', 'Java', 'Go', 'Ruby', 'PHP', '.NET'],
      },
      {
        key: 'frontend',
        name: 'domain_frontend',
        icon: FaDesktop,
        description: 'domain_frontend_desc',
        children: [
          'React',
          'Vue',
          'Angular',
          'Svelte',
          'JavaScript',
          'TypeScript',
          'HTML/CSS',
        ],
      },
      {
        key: 'devops',
        name: 'domain_devops',
        icon: FaGears,
        description: 'domain_devops_desc',
        children: [
          'Docker',
          'Kubernetes',
          'CI/CD',
          'AWS',
          'Azure',
          'GCP',
          'Linux',
        ],
      },
      {
        key: 'security',
        name: 'domain_security',
        icon: FaShieldHalved,
        description: 'domain_security_desc',
        children: [
          'Penetration Testing',
          'Cryptography',
          'Network Security',
          'Web Security',
        ],
      },
      {
        key: 'datascience',
        name: 'domain_datascience',
        icon: FaChartLine,
        description: 'domain_datascience_desc',
        children: ['Python', 'R', 'SQL', 'Statistics', 'Data Visualization'],
      },
      {
        key: 'mobile',
        name: 'domain_mobile',
        icon: FaMobileScreen,
        description: 'domain_mobile_desc',
        children: [
          'iOS',
          'Android',
          'React Native',
          'Flutter',
          'Kotlin',
          'Swift',
        ],
      },
      {
        key: 'aiml',
        name: 'domain_aiml',
        icon: FaRobot,
        description: 'domain_aiml_desc',
        children: [
          'Machine Learning',
          'Deep Learning',
          'NLP',
          'Computer Vision',
        ],
      },
      {
        key: 'game',
        name: 'domain_game',
        icon: FaGamepad,
        description: 'domain_game_desc',
        children: [
          'Unity',
          'Unreal Engine',
          'Game Design',
          'Graphics Programming',
        ],
      },
      {
        key: 'cloud',
        name: 'domain_cloud',
        icon: FaCloud,
        description: 'domain_cloud_desc',
        children: ['AWS', 'Azure', 'GCP', 'Cloud Architecture', 'Serverless'],
      },
      {
        key: 'blockchain',
        name: 'domain_blockchain',
        icon: FaLink,
        description: 'domain_blockchain_desc',
        children: ['Smart Contracts', 'DApps', 'Cryptocurrency', 'Web3'],
      },
      {
        key: 'iot',
        name: 'domain_iot',
        icon: FaMicrochip,
        description: 'domain_iot_desc',
        children: [
          'Embedded Systems',
          'Sensors',
          'IoT Protocols',
          'Edge Computing',
        ],
      },
      {
        key: 'qa',
        name: 'domain_qa',
        icon: FaBug,
        description: 'domain_qa_desc',
        children: [
          'Test Automation',
          'Manual Testing',
          'Performance Testing',
          'Security Testing',
        ],
      },
      {
        key: 'embedded',
        name: 'domain_embedded',
        icon: FaMicrochip,
        description: 'domain_embedded_desc',
        children: ['C', 'C++', 'ARM', 'RTOS', 'IoT', 'Firmware'],
      },
    ],
  },
  {
    key: 'design',
    group: 'domain_group_design',
    icon: FaPalette,
    domains: [
      {
        key: 'uiux',
        name: 'domain_uiux',
        icon: FaLaptopCode,
        description: 'domain_uiux_desc',
        children: [
          'UX Research',
          'UI Design',
          'Interaction Design',
          'Usability Testing',
          'Information Architecture',
          'Design Systems',
        ],
      },
      {
        key: 'graphic',
        name: 'domain_graphic',
        icon: FaPaintbrush,
        description: 'domain_graphic_desc',
        children: [
          'Brand Design',
          'Print Design',
          'Digital Design',
          'Motion Graphics',
          'Typography',
          'Visual Identity',
        ],
      },
      {
        key: 'product',
        name: 'domain_product',
        icon: FaObjectGroup,
        description: 'domain_product_desc',
        children: [
          'Product Strategy',
          'User Research',
          'Product Roadmap',
          'Agile Management',
          'Product Analytics',
          'Go-to-Market',
        ],
      },
    ],
  },
  {
    key: 'business',
    group: 'domain_group_business',
    icon: FaChartLine,
    domains: [
      {
        key: 'business_strategy',
        name: 'domain_business_strategy',
        icon: FaChartLine,
        description: 'domain_business_strategy_desc',
        children: [
          'Strategic Planning',
          'Business Development',
          'Digital Transformation',
          'E-commerce Strategy',
          'Innovation Management',
        ],
      },
      {
        key: 'marketing',
        name: 'domain_marketing',
        icon: FaBullhorn,
        description: 'domain_marketing_desc',
        children: [
          'Digital Marketing',
          'Content Marketing',
          'Social Media',
          'Brand Strategy',
          'Market Research',
        ],
      },
      {
        key: 'sales',
        name: 'domain_sales',
        icon: FaHandshake,
        description: 'domain_sales_desc',
        children: [
          'B2B Sales',
          'B2C Sales',
          'Sales Strategy',
          'Account Management',
          'Lead Generation',
        ],
      },
      {
        key: 'finance_accounting',
        name: 'domain_finance_accounting',
        icon: FaChartLine,
        description: 'domain_finance_accounting_desc',
        children: [
          'Financial Analysis',
          'Accounting',
          'Investment',
          'Risk Management',
          'Tax Planning',
        ],
      },
      {
        key: 'hr',
        name: 'domain_hr',
        icon: FaPeopleGroup,
        description: 'domain_hr_desc',
        children: [
          'Talent Acquisition',
          'Employee Development',
          'Performance Management',
          'Compensation & Benefits',
          'HR Analytics',
        ],
      },
    ],
  },
  {
    key: 'legal',
    group: 'domain_group_legal',
    icon: FaScaleBalanced,
    domains: [
      {
        key: 'legal',
        name: 'domain_legal',
        icon: FaScaleBalanced,
        description: 'domain_legal_desc',
        children: [
          'Corporate Law',
          'Intellectual Property',
          'Contract Law',
          'Employment Law',
          'Regulatory Compliance',
        ],
      },
    ],
  },
  {
    key: 'education',
    group: 'domain_group_education',
    icon: FaGraduationCap,
    domains: [
      {
        key: 'teaching',
        name: 'domain_teaching',
        icon: FaGraduationCap,
        description: 'domain_teaching_desc',
        children: [
          'K-12 Education',
          'Higher Education',
          'Online Learning',
          'Special Education',
          'STEM Education',
          'Language Teaching',
        ],
      },
      {
        key: 'curriculum',
        name: 'domain_curriculum',
        icon: FaGraduationCap,
        description: 'domain_curriculum_desc',
        children: [
          'Curriculum Development',
          'Educational Technology',
          'Assessment Design',
          'Learning Analytics',
          'Instructional Design',
          'E-learning Development',
        ],
      },
    ],
  },
  {
    key: 'arts',
    group: 'domain_group_arts',
    icon: FaMasksTheater,
    domains: [
      {
        key: 'visual_arts',
        name: 'domain_visual_arts',
        icon: FaPaintbrush,
        description: 'domain_visual_arts_desc',
        children: [
          'Digital Art',
          'Traditional Art',
          'Animation',
          'Photography',
          'Illustration',
          'Sculpture',
        ],
      },
      {
        key: 'performing_arts',
        name: 'domain_performing_arts',
        icon: FaMasksTheater,
        description: 'domain_performing_arts_desc',
        children: [
          'Music Performance',
          'Theater Arts',
          'Dance',
          'Film Production',
          'Stage Direction',
          'Performance Art',
        ],
      },
      {
        key: 'conservatory_music',
        name: 'domain_conservatory_music',
        icon: FaMasksTheater,
        description: 'domain_conservatory_music_desc',
        children: [
          'Music Theory',
          'Instrumental Performance',
          'Orchestration',
          'Composition',
          'Conducting',
          'Vocal Studies',
        ],
      },
    ],
  },
  {
    key: 'science',
    group: 'domain_group_science',
    icon: FaMicroscope,
    domains: [
      {
        key: 'research',
        name: 'domain_research',
        icon: FaMicroscope,
        description: 'domain_research_desc',
        children: [
          'Research Methods',
          'Data Analysis',
          'Scientific Writing',
          'Lab Techniques',
        ],
      },
      {
        key: 'applied_science',
        name: 'domain_applied_science',
        icon: FaMicroscope,
        description: 'domain_applied_science_desc',
        children: ['Physics', 'Chemistry', 'Biology', 'Environmental Science'],
      },
    ],
  },
  {
    key: 'engineering',
    group: 'domain_group_engineering',
    icon: FaGears,
    domains: [
      {
        key: 'mechanical',
        name: 'domain_mechanical',
        icon: FaGears,
        description: 'domain_mechanical_desc',
        children: [
          'CAD',
          'SolidWorks',
          'Thermodynamics',
          'Materials',
          'Manufacturing',
        ],
      },
      {
        key: 'electrical',
        name: 'domain_electrical',
        icon: FaMicrochip,
        description: 'domain_electrical_desc',
        children: [
          'Điện công nghiệp',
          'Điện tử công suất',
          'Vi mạch',
          'FPGA',
          'Chip Design',
          'Điện tử số',
        ],
      },
      {
        key: 'embedded',
        name: 'domain_embedded',
        icon: FaMicrochip,
        description: 'domain_embedded_desc',
        children: ['C', 'C++', 'ARM', 'RTOS', 'IoT', 'Firmware'],
      },
      {
        key: 'hvac_piping',
        name: 'domain_hvac_piping',
        icon: FaGears,
        description: 'domain_hvac_piping_desc',
        children: [
          'HVAC',
          'Piping',
          'Ductwork',
          'Revit MEP',
          'Chiller',
          'Pump',
          'Fire Protection',
          'Plumbing',
        ],
      },
    ],
  },
  {
    key: 'hospitality',
    group: 'domain_group_hospitality',
    icon: FaHotel,
    domains: [
      {
        key: 'tourism',
        name: 'domain_tourism',
        icon: FaPlane,
        description: 'domain_tourism_desc',
        children: [
          'Tour Planning',
          'Tourism Management',
          'Travel Services',
          'Destination Marketing',
        ],
      },
      {
        key: 'hotel_management',
        name: 'domain_hotel_management',
        icon: FaHotel,
        description: 'domain_hotel_management_desc',
        children: [
          'Hotel Operations',
          'Front Office',
          'Housekeeping',
          'Food & Beverage',
          'Revenue Management',
        ],
      },
      {
        key: 'restaurant_management',
        name: 'domain_restaurant_management',
        icon: FaUtensils,
        description: 'domain_restaurant_management_desc',
        children: [
          'Restaurant Operations',
          'Kitchen Management',
          'Menu Planning',
          'Food Safety',
          'Customer Service',
        ],
      },
    ],
  },
  {
    key: 'logistics',
    group: 'domain_group_logistics',
    icon: FaTruck,
    domains: [
      {
        key: 'transportation',
        name: 'domain_transportation',
        icon: FaTruck,
        description: 'domain_transportation_desc',
        children: [
          'Fleet Management',
          'Route Optimization',
          'Transportation Planning',
          'Shipping Operations',
        ],
      },
      {
        key: 'logistics_management',
        name: 'domain_logistics_management',
        icon: FaBox,
        description: 'domain_logistics_management_desc',
        children: [
          'Supply Chain Management',
          'Warehouse Operations',
          'Inventory Management',
          'Distribution Planning',
        ],
      },
    ],
  },
  {
    key: 'manufacturing',
    group: 'domain_group_manufacturing',
    icon: FaIndustry,
    domains: [
      {
        key: 'production',
        name: 'domain_production',
        icon: FaIndustry,
        description: 'domain_production_desc',
        children: [
          'Production Planning',
          'Quality Control',
          'Process Optimization',
          'Manufacturing Operations',
        ],
      },
      {
        key: 'skilled_labor',
        name: 'domain_skilled_labor',
        icon: FaScrewdriverWrench,
        description: 'domain_skilled_labor_desc',
        children: [
          'Assembly',
          'Machine Operation',
          'Maintenance',
          'Craftsmanship',
        ],
      },
    ],
  },
  {
    key: 'healthcare',
    group: 'domain_group_healthcare',
    icon: FaHospital,
    domains: [
      {
        key: 'nursing',
        name: 'domain_nursing',
        icon: FaUserDoctor,
        description: 'domain_nursing_desc',
        children: [
          'Clinical Nursing',
          'Emergency Care',
          'Patient Care',
          'Medical Procedures',
        ],
      },
      {
        key: 'pharmacy',
        name: 'domain_pharmacy',
        icon: FaHospital,
        description: 'domain_pharmacy_desc',
        children: [
          'Pharmacology',
          'Drug Interactions',
          'Pharmaceutical Care',
          'Clinical Pharmacy',
        ],
      },
      {
        key: 'healthcare_admin',
        name: 'domain_healthcare_admin',
        icon: FaHospital,
        description: 'domain_healthcare_admin_desc',
        children: [
          'Hospital Management',
          'Healthcare Policy',
          'Medical Records',
          'Healthcare Operations',
        ],
      },
    ],
  },
  {
    key: 'environmental',
    group: 'domain_group_environmental',
    icon: FaLeaf,
    domains: [
      {
        key: 'environmental_management',
        name: 'domain_environmental_management',
        icon: FaLeaf,
        description: 'domain_environmental_management_desc',
        children: [
          'Environmental Impact Assessment',
          'Waste Management',
          'Conservation',
          'Sustainability',
        ],
      },
      {
        key: 'renewable_energy',
        name: 'domain_renewable_energy',
        icon: FaLeaf,
        description: 'domain_renewable_energy_desc',
        children: [
          'Solar Energy',
          'Wind Power',
          'Hydroelectric',
          'Energy Storage',
        ],
      },
    ],
  },
  {
    key: 'agriculture',
    group: 'domain_group_agriculture',
    icon: FaSeedling,
    domains: [
      {
        key: 'agribusiness',
        name: 'domain_agribusiness',
        icon: FaSeedling,
        description: 'domain_agribusiness_desc',
        children: [
          'Farm Management',
          'Agricultural Economics',
          'Supply Chain',
          'Food Production',
        ],
      },
      {
        key: 'food_science',
        name: 'domain_food_science',
        icon: FaSeedling,
        description: 'domain_food_science_desc',
        children: [
          'Food Processing',
          'Food Safety',
          'Product Development',
          'Quality Control',
        ],
      },
    ],
  },
  {
    key: 'media',
    group: 'domain_group_media',
    icon: FaNewspaper,
    domains: [
      {
        key: 'journalism',
        name: 'domain_journalism',
        icon: FaNewspaper,
        description: 'domain_journalism_desc',
        children: [
          'News Writing',
          'Investigative Journalism',
          'Digital Media',
          'Broadcasting',
        ],
      },
      {
        key: 'public_relations',
        name: 'domain_public_relations',
        icon: FaNewspaper,
        description: 'domain_public_relations_desc',
        children: [
          'Media Relations',
          'Crisis Communication',
          'Corporate Communications',
          'Public Affairs',
        ],
      },
    ],
  },
  {
    key: 'psychology',
    group: 'domain_group_psychology',
    icon: FaBrain,
    domains: [
      {
        key: 'clinical_psychology',
        name: 'domain_clinical_psychology',
        icon: FaBrain,
        description: 'domain_clinical_psychology_desc',
        children: [
          'Psychological Assessment',
          'Therapy',
          'Mental Health',
          'Behavioral Analysis',
        ],
      },
      {
        key: 'organizational_psychology',
        name: 'domain_organizational_psychology',
        icon: FaBrain,
        description: 'domain_organizational_psychology_desc',
        children: [
          'Workplace Behavior',
          'Employee Assessment',
          'Team Dynamics',
          'Leadership Development',
        ],
      },
    ],
  },
  {
    key: 'architecture',
    group: 'domain_group_architecture',
    icon: FaBuilding,
    domains: [
      {
        key: 'architectural_design',
        name: 'domain_architectural_design',
        icon: FaBuilding,
        description: 'domain_architectural_design_desc',
        children: [
          'Building Design',
          'CAD',
          'Sustainable Architecture',
          'Urban Planning',
        ],
      },
      {
        key: 'construction_management',
        name: 'domain_construction_management',
        icon: FaBuilding,
        description: 'domain_construction_management_desc',
        children: [
          'Project Management',
          'Construction Planning',
          'Cost Estimation',
          'Site Supervision',
        ],
      },
    ],
  },
  {
    key: 'banking',
    group: 'domain_group_banking',
    icon: FaMoneyBillTrendUp,
    domains: [
      {
        key: 'retail_banking',
        name: 'domain_retail_banking',
        icon: FaCreditCard,
        description: 'domain_retail_banking_desc',
        children: [
          'Personal Banking',
          'Credit Cards',
          'Mortgages',
          'Consumer Lending',
          'Digital Banking',
        ],
      },
      {
        key: 'investment_banking',
        name: 'domain_investment_banking',
        icon: FaChartPie,
        description: 'domain_investment_banking_desc',
        children: [
          'Corporate Finance',
          'Mergers & Acquisitions',
          'Capital Markets',
          'Securities Trading',
          'Financial Advisory',
        ],
      },
      {
        key: 'wealth_management',
        name: 'domain_wealth_management',
        icon: FaVault,
        description: 'domain_wealth_management_desc',
        children: [
          'Portfolio Management',
          'Estate Planning',
          'Private Banking',
          'Asset Management',
          'Investment Strategy',
        ],
      },
      {
        key: 'risk_compliance',
        name: 'domain_risk_compliance',
        icon: FaShieldHalved,
        description: 'domain_risk_compliance_desc',
        children: [
          'Risk Assessment',
          'Regulatory Compliance',
          'Anti-Money Laundering',
          'Credit Risk',
          'Market Risk',
        ],
      },
    ],
  },
  {
    key: 'investment',
    group: 'domain_group_investment',
    icon: FaChartLine,
    domains: [
      {
        key: 'securities_trading',
        name: 'domain_securities_trading',
        icon: FaArrowTrendUp,
        description: 'domain_securities_trading_desc',
        children: [
          'Equity Trading',
          'Fixed Income',
          'Derivatives',
          'Forex Trading',
          'Technical Analysis',
        ],
      },
      {
        key: 'portfolio_management',
        name: 'domain_portfolio_management',
        icon: FaChartPie,
        description: 'domain_portfolio_management_desc',
        children: [
          'Asset Allocation',
          'Risk Management',
          'Performance Analysis',
          'Investment Strategy',
          'Fund Management',
        ],
      },
      {
        key: 'alternative_investments',
        name: 'domain_alternative_investments',
        icon: FaCoins,
        description: 'domain_alternative_investments_desc',
        children: [
          'Private Equity',
          'Hedge Funds',
          'Real Estate Investment',
          'Venture Capital',
          'Cryptocurrency',
        ],
      },
      {
        key: 'market_analysis',
        name: 'domain_market_analysis',
        icon: FaChartLine,
        description: 'domain_market_analysis_desc',
        children: [
          'Fundamental Analysis',
          'Market Research',
          'Economic Analysis',
          'Quantitative Analysis',
          'ESG Investment',
        ],
      },
    ],
  },
  {
    key: 'insurance',
    group: 'domain_group_insurance',
    icon: FaShieldHeart,
    domains: [
      {
        key: 'life_health_insurance',
        name: 'domain_life_health_insurance',
        icon: FaShieldHeart,
        description: 'domain_life_health_insurance_desc',
        children: [
          'Life Insurance',
          'Health Insurance',
          'Medical Claims',
          'Group Insurance',
          'Insurance Planning',
        ],
      },
      {
        key: 'property_casualty',
        name: 'domain_property_casualty',
        icon: FaHouseChimney,
        description: 'domain_property_casualty_desc',
        children: [
          'Property Insurance',
          'Auto Insurance',
          'Liability Coverage',
          'Commercial Insurance',
          'Risk Assessment',
        ],
      },
      {
        key: 'insurance_underwriting',
        name: 'domain_insurance_underwriting',
        icon: FaCalculator,
        description: 'domain_insurance_underwriting_desc',
        children: [
          'Risk Evaluation',
          'Policy Pricing',
          'Claims Analysis',
          'Actuarial Science',
          'Underwriting Guidelines',
        ],
      },
      {
        key: 'claims_management',
        name: 'domain_claims_management',
        icon: FaCarSide,
        description: 'domain_claims_management_desc',
        children: [
          'Claims Processing',
          'Investigation',
          'Settlement',
          'Fraud Detection',
          'Customer Service',
        ],
      },
    ],
  },
];
