import { DomainGroup } from '@/utils/types/Domain';
import {
  FaServer,
  FaDesktop,
  FaGears,
  FaShieldHalved,
  FaChartLine,
  FaMobileScreen,
  FaRobot,
  FaGamepad,
  FaCloud,
  FaLink,
  FaMicrochip,
  FaBug,
  FaGraduationCap,
  FaMasksTheater,
  FaMicroscope,
  FaPaintbrush,
  FaPalette,
  FaScaleBalanced,
  FaBullhorn,
  FaHandshake,
  FaPeopleGroup,
  FaUserDoctor,
} from 'react-icons/fa6';

export const domainGroups: DomainGroup[] = [
  {
    key: 'technology',
    group: 'domain_group_technology',
    icon: FaGears,
    domains: [
      {
        key: 'backend',
        name: 'domain_backend',
        icon: FaServer,
        description: 'domain_backend_desc',
        children: ['Node.js', 'Python', 'Java', 'Go', 'Ruby', 'PHP', '.NET'],
      },
      {
        key: 'frontend',
        name: 'domain_frontend',
        icon: FaDesktop,
        description: 'domain_frontend_desc',
        children: [
          'React',
          'Vue',
          'Angular',
          'Svelte',
          'JavaScript',
          'TypeScript',
          'HTML/CSS',
        ],
      },
      {
        key: 'devops',
        name: 'domain_devops',
        icon: FaGears,
        description: 'domain_devops_desc',
        children: [
          'Docker',
          'Kubernetes',
          'CI/CD',
          'AWS',
          'Azure',
          'GCP',
          'Linux',
        ],
      },
      {
        key: 'security',
        name: 'domain_security',
        icon: FaShieldHalved,
        description: 'domain_security_desc',
        children: [
          'Penetration Testing',
          'Cryptography',
          'Network Security',
          'Web Security',
        ],
      },
      {
        key: 'datascience',
        name: 'domain_datascience',
        icon: FaChartLine,
        description: 'domain_datascience_desc',
        children: ['Python', 'R', 'SQL', 'Statistics', 'Data Visualization'],
      },
      {
        key: 'mobile',
        name: 'domain_mobile',
        icon: FaMobileScreen,
        description: 'domain_mobile_desc',
        children: [
          'iOS',
          'Android',
          'React Native',
          'Flutter',
          'Kotlin',
          'Swift',
        ],
      },
      {
        key: 'aiml',
        name: 'domain_aiml',
        icon: FaRobot,
        description: 'domain_aiml_desc',
        children: [
          'Machine Learning',
          'Deep Learning',
          'NLP',
          'Computer Vision',
        ],
      },
      {
        key: 'game',
        name: 'domain_game',
        icon: FaGamepad,
        description: 'domain_game_desc',
        children: [
          'Unity',
          'Unreal Engine',
          'Game Design',
          'Graphics Programming',
        ],
      },
      {
        key: 'cloud',
        name: 'domain_cloud',
        icon: FaCloud,
        description: 'domain_cloud_desc',
        children: ['AWS', 'Azure', 'GCP', 'Cloud Architecture', 'Serverless'],
      },
      {
        key: 'blockchain',
        name: 'domain_blockchain',
        icon: FaLink,
        description: 'domain_blockchain_desc',
        children: ['Smart Contracts', 'DApps', 'Cryptocurrency', 'Web3'],
      },
      {
        key: 'iot',
        name: 'domain_iot',
        icon: FaMicrochip,
        description: 'domain_iot_desc',
        children: [
          'Embedded Systems',
          'Sensors',
          'IoT Protocols',
          'Edge Computing',
        ],
      },
      {
        key: 'qa',
        name: 'domain_qa',
        icon: FaBug,
        description: 'domain_qa_desc',
        children: [
          'Test Automation',
          'Manual Testing',
          'Performance Testing',
          'Security Testing',
        ],
      },
      {
        key: 'embedded',
        name: 'domain_embedded',
        icon: FaMicrochip,
        description: 'domain_embedded_desc',
        children: ['C', 'C++', 'ARM', 'RTOS', 'IoT', 'Firmware'],
      },
    ],
  },
  {
    key: 'design',
    group: 'domain_group_design',
    icon: FaPalette,
    domains: [
      {
        key: 'uiux',
        name: 'domain_uiux',
        icon: FaPalette,
        description: 'domain_uiux_desc',
      },
      {
        key: 'graphic',
        name: 'domain_graphic',
        icon: FaPaintbrush,
        description: 'domain_graphic_desc',
      },
      {
        key: 'product',
        name: 'domain_product',
        icon: FaPalette,
        description: 'domain_product_desc',
      },
    ],
  },
  {
    key: 'business',
    group: 'domain_group_business',
    icon: FaChartLine,
    domains: [
      {
        key: 'business_strategy',
        name: 'domain_business_strategy',
        icon: FaChartLine,
        description: 'domain_business_strategy_desc',
      },
      {
        key: 'marketing',
        name: 'domain_marketing',
        icon: FaBullhorn,
        description: 'domain_marketing_desc',
      },
      {
        key: 'sales',
        name: 'domain_sales',
        icon: FaHandshake,
        description: 'domain_sales_desc',
      },
      {
        key: 'hr',
        name: 'domain_hr',
        icon: FaPeopleGroup,
        description: 'domain_hr_desc',
      },
    ],
  },
  {
    key: 'legal',
    group: 'domain_group_legal',
    icon: FaScaleBalanced,
    domains: [
      {
        key: 'legal',
        name: 'domain_legal',
        icon: FaScaleBalanced,
        description: 'domain_legal_desc',
      },
      {
        key: 'medical',
        name: 'domain_medical',
        icon: FaUserDoctor,
        description: 'domain_medical_desc',
      },
    ],
  },
  {
    key: 'education',
    group: 'domain_group_education',
    icon: FaGraduationCap,
    domains: [
      {
        key: 'teaching',
        name: 'domain_teaching',
        icon: FaGraduationCap,
        description: 'domain_teaching_desc',
        children: [
          'K-12 Education',
          'Higher Education',
          'Online Learning',
          'Special Education',
        ],
      },
      {
        key: 'curriculum',
        name: 'domain_curriculum',
        icon: FaGraduationCap,
        description: 'domain_curriculum_desc',
        children: [
          'Curriculum Development',
          'Educational Technology',
          'Assessment',
          'Pedagogy',
        ],
      },
    ],
  },
  {
    key: 'arts',
    group: 'domain_group_arts',
    icon: FaMasksTheater,
    domains: [
      {
        key: 'visual_arts',
        name: 'domain_visual_arts',
        icon: FaPaintbrush,
        description: 'domain_visual_arts_desc',
        children: [
          'Digital Art',
          'Traditional Art',
          'Animation',
          'Photography',
        ],
      },
      {
        key: 'performing_arts',
        name: 'domain_performing_arts',
        icon: FaMasksTheater,
        description: 'domain_performing_arts_desc',
        children: ['Music', 'Theater', 'Dance', 'Film'],
      },
      {
        key: 'conservatory_music',
        name: 'domain_conservatory_music',
        icon: FaMasksTheater,
        description: 'domain_conservatory_music_desc',
        children: [
          'Lý thuyết âm nhạc',
          'Biểu diễn nhạc cụ',
          'Hòa âm phối khí',
          'Sáng tác',
          'Chỉ huy dàn nhạc',
          'Thanh nhạc',
        ],
      },
    ],
  },
  {
    key: 'science',
    group: 'domain_group_science',
    icon: FaMicroscope,
    domains: [
      {
        key: 'research',
        name: 'domain_research',
        icon: FaMicroscope,
        description: 'domain_research_desc',
        children: [
          'Research Methods',
          'Data Analysis',
          'Scientific Writing',
          'Lab Techniques',
        ],
      },
      {
        key: 'applied_science',
        name: 'domain_applied_science',
        icon: FaMicroscope,
        description: 'domain_applied_science_desc',
        children: ['Physics', 'Chemistry', 'Biology', 'Environmental Science'],
      },
    ],
  },
  {
    key: 'engineering',
    group: 'domain_group_engineering',
    icon: FaGears,
    domains: [
      {
        key: 'mechanical',
        name: 'domain_mechanical',
        icon: FaGears,
        description: 'domain_mechanical_desc',
        children: [
          'CAD',
          'SolidWorks',
          'Thermodynamics',
          'Materials',
          'Manufacturing',
        ],
      },
      {
        key: 'electrical',
        name: 'domain_electrical',
        icon: FaMicrochip,
        description: 'domain_electrical_desc',
        children: [
          'Điện công nghiệp',
          'Điện tử công suất',
          'Vi mạch',
          'FPGA',
          'Chip Design',
          'Điện tử số',
        ],
      },
      {
        key: 'hvac_piping',
        name: 'domain_hvac_piping',
        icon: FaGears,
        description: 'domain_hvac_piping_desc',
        children: [
          'HVAC',
          'Piping',
          'Ductwork',
          'Revit MEP',
          'Chiller',
          'Pump',
          'Fire Protection',
          'Plumbing',
        ],
      },
    ],
  },
];
